-- M-SEC-6 — allow the audit event 'account_link_issued' (docs/security-fixes-2026-10-plan.md §15.7, owner point A).
-- Approved by the owner 2026-10-04. Pre-check: 0 existing events rows outside the new list.
--
-- Every one-time invite / recovery link generated by an Edge Function (enable-client-login,
-- enable-caregiver-login, approve-caregiver-registration, create-user, admin-reset-password) writes an
-- events row: actor_id = the staff member, subject_type 'user' + subject_id = the account,
-- payload {link_type: 'invite'|'recovery', function}, occurred_at = time. The link / token is NEVER
-- stored. The functions insert directly and fail closed (no audit row -> no link), so this value must
-- exist in the CHECK list before they are deployed.
--
-- Change: re-create events_event_type_check with the exact current list + 'account_link_issued'.
-- Drop + add are ONE ALTER TABLE statement, so they are atomic on their own (never a window
-- without the constraint, and a failure leaves the old constraint in place).
-- No data change; no function or grant change (CLAUDE.md #13/#14 not triggered).

ALTER TABLE public.events
  DROP CONSTRAINT events_event_type_check,
  ADD CONSTRAINT events_event_type_check CHECK (event_type = ANY (ARRAY[
  'caregiver_application_received', 'caregiver_approved', 'caregiver_rejected',
  'care_request_received', 'care_request_converted_to_client',
  'shift_created', 'shift_assigned', 'shift_filled', 'shift_completed', 'shift_cancelled', 'shift_no_show',
  'caregiver_pickup', 'assignment_released', 'rating_added',
  'time_entry_submitted', 'time_entry_approved', 'earnings_computed',
  'account_link_issued'
]::text[]));

-- Verify (read-only): SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = 'events_event_type_check';
-- Rollback: re-create the constraint without 'account_link_issued' (only after deleting any such rows).
